### ISSUE TITLE
SVG 2 proposed features

### ISSUE THREAD

**Issue by liamquin** [RazrFalcon/libresvg#23]
Do you implement any of the features proposed for SVG 2? Are you planning to?

Thanks!

**Comment by RazrFalcon** [comment]
No, because it's not an official standard yet.

No, currently it's not planned. Mostly because backend should support it too. `stroke-linejoin:arcs` for example.

**Comment by liamquin** [comment]
On Tue, 2017-12-19 at 08:53 +0000, Evgeniy Reizner wrote:
> No, because it's not an official standard yet.
> 
> No, currently it's not planned. Mostly because backend should support
> it too. `stroke-linejoin:arcs` for example.

Thanks for responding. SVG 2 won't become a Recommendation until we get
interoperability by having tests (we're working on that) and two or
more implementations. Some features won't make the cut, and for sure
there will be changes, but in the next few months we'll be working out
which features to cut, and comments on any that would be hard to
implement in libresvg would be useful feedback. Anyway, just checking
in, thanks again.

-- 
Liam Quin, W3C, http://www.w3.org/People/Quin/
Staff contact for Verifiable Claims WG, SVG WG, XQuery WG

Web slave for http://www.fromoldbooks.org/

**Comment by RazrFalcon** [comment]
I don't read the SVG 2 spec yet, so I don't know how much changes it has. At some point, it may be easier to create resvg2, just for svg2.
