### ISSUE TITLE
dom module types are not public

### ISSUE THREAD

**Issue by dylanede** [RazrFalcon/libresvg#24]
This makes working with the `Document` type difficult. A simple fix is to `pub use dom::*;` in src/lib.rs.

**Comment by RazrFalcon** [comment]
The `Document` internals should not be public. Why do you need this?

> A simple fix is to pub use dom::*; in src/lib.rs.

There are no docs, so it's not that simple =)

**Comment by dylanede** [comment]
Well, `Document` contains `Element`s publicly, but this type is not made public, nor are the types used by the transitive public members of `Element`.

**Comment by RazrFalcon** [comment]
It's because you shouldn't use them outside the backend code. The `Document` is just a container of SVG data. You should not care about what inside. You can treat it as an opaque pointer.

**Comment by dylanede** [comment]
In that case you should probably make the members of `Document` `pub(crate)` instead of `pub`.

Though if someone wanted to use the document processing capabilities of resvg for writing their own SVG renderer, making these things public would be very handy (i.e. that's what I'm doing right now, with a fork making these types public).

**Comment by RazrFalcon** [comment]
Hm... The idea is the backend code should be inside the library. But if you want to use it just as preprocessor (all backend are optional already), then yes - it will be handy.

I will make them public and add docs and `Debug`.

**Comment by dylanede** [comment]
Thanks!

**Comment by RazrFalcon** [comment]
Done. Documentation is pretty simple, but I hope it help.

**Comment by dylanede** [comment]
Thanks again
