### ISSUE TITLE
Add nanosvg to comparison chart

### ISSUE THREAD

**Issue by est31** [RazrFalcon/libresvg#30]
It would be interesting to compare nanosvg to the other implementations: https://github.com/memononen/nanosvg

**Comment by RazrFalcon** [comment]
It's too primitive. There is nothing to compare.

**Comment by est31** [comment]
@RazrFalcon that might be obvious to you, but if it is inside the comparison chart, it would be obvious to everyone.

**Comment by RazrFalcon** [comment]
I'll try it.

**Comment by RazrFalcon** [comment]
Looks like it doesn't support percent values in the `width` and `height` attributes, so it's automatically fails all the test.

I have to change all the tests to make it draw at least something...

**Comment by RazrFalcon** [comment]
It also doesn't support text rendering, so again: "There is nothing to compare".

I can add a not to the readme, that `nanosvg` is out of scope because it's to primitive. I don't see a point in adding a new line to the chart which will be completely red.

**Comment by est31** [comment]
Okay. Thanks for looking!
